/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graduation.project;

/**
 *
 * @author leina
 */
public class chooseSession extends javax.swing.JFrame {

    String sessionType = null;
    /**
     * Creates new form Training
     */
    public chooseSession() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Jsad = new javax.swing.JButton();
        JFear = new javax.swing.JButton();
        JHappy = new javax.swing.JButton();
        JAnger = new javax.swing.JButton();
        JSurprise = new javax.swing.JButton();
        JDisgust = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setText("Choose a session");

        Jsad.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        Jsad.setText("Sadness");
        Jsad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JsadActionPerformed(evt);
            }
        });

        JFear.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        JFear.setText("Fear");
        JFear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JFearActionPerformed(evt);
            }
        });

        JHappy.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        JHappy.setText("Happiness");
        JHappy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JHappyActionPerformed(evt);
            }
        });

        JAnger.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        JAnger.setText("Anger");
        JAnger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JAngerActionPerformed(evt);
            }
        });

        JSurprise.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        JSurprise.setText("Surprise");
        JSurprise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JSurpriseActionPerformed(evt);
            }
        });

        JDisgust.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        JDisgust.setText("Disgust");
        JDisgust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JDisgustActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JHappy, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JAnger, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JSurprise, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Jsad, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JFear, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JDisgust, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jsad, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JFear, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JDisgust, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JHappy, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JAnger, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JSurprise, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JsadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JsadActionPerformed
    sessionType="sadness";
    viewSession(sessionType);
    }//GEN-LAST:event_JsadActionPerformed

    private void JFearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JFearActionPerformed
    sessionType="Fear";
    viewSession(sessionType);
    
    }//GEN-LAST:event_JFearActionPerformed

    private void JDisgustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JDisgustActionPerformed
    sessionType="Disgust";
    viewSession(sessionType);
    
    }//GEN-LAST:event_JDisgustActionPerformed

    private void JHappyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JHappyActionPerformed
    sessionType="Happiness";
    viewSession(sessionType);
    
    }//GEN-LAST:event_JHappyActionPerformed

    private void JAngerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JAngerActionPerformed
    sessionType="Anger";
    viewSession(sessionType);
    
    }//GEN-LAST:event_JAngerActionPerformed

    private void JSurpriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JSurpriseActionPerformed
    sessionType="Surprise";
    viewSession(sessionType);
    
    }//GEN-LAST:event_JSurpriseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(chooseSession.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(chooseSession.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(chooseSession.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(chooseSession.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new chooseSession().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JAnger;
    private javax.swing.JButton JDisgust;
    private javax.swing.JButton JFear;
    private javax.swing.JButton JHappy;
    private javax.swing.JButton JSurprise;
    private javax.swing.JButton Jsad;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    private void viewSession(String sessionType) {
        switch(sessionType){
        case "sadness":
            
            
            ;break;
        case "Fear": ;break;
        case "Disgust": ;break;
        case "Anger": ;break;
        case "Surprise": ;break;
        case "Happiness": ;break;
        
        }
    }
}
